application: take2
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /(export.*|import|importfile)
  script: take2export.py

- url: /search.*
  script: take2search.py

- url: /(index|lookup)
  script: take2contact_index.py

- url: /(new.*|edit.*|save.*|attic.*|deattic.*)
  script: take2edit.py
  login: required

- url: /geo.*
  script: take2geo.py
  login: required
