application: take2nitz
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /(export.*|import.*)
  script: take2export.py

- url: (/|/search.*)
  script: take2search.py

- url: (/login|/_ah/login_required|/welcome|/openid_login|/signup)
  script: take2login.py

- url: /(index|lookup|indexpurge|fix)
  script: take2index.py

- url: /(new.*|edit.*|save.*|attic.*|deattic.*)
  script: take2edit.py
  login: required

- url: /location.*
  script: take2geo.py
  login: required

- url: /share.*
  script: take2share.py
  login: required

- url: /map.*
  script: take2map.py
