application: take2
version: 1
runtime: python
api_version: 1

handlers:
- url: /export.*
  script: take2export.py

- url: /import
  script: take2export.py

- url: /search.*
  script: take2edit.py

- url: /(edit.*|save.*)
  script: take2edit.py
  login: required

